<?php

use App\Services\ResumeParser\Line;
use App\Services\ResumeParser\ResumeLineFeaturizer;

/**
 * Phase 1 of the learned resume parser. Everything downstream (labels,
 * training, assembly) is a function of what the featurizer saw, so these
 * assertions are about extraction fidelity rather than parsed output.
 *
 * Both fixtures are generated by this project (the live resume template, and a
 * hand-built two-column layout), so no third-party or personal document is
 * committed.
 */
beforeEach(function () {
    // Pinned so feature assertions never depend on what the database happens
    // to hold. Cleared again in afterEach.
    ResumeLineFeaturizer::setGazetteers([
        'skills' => ['php', 'laravel', 'javascript', 'mysql', 'figma', 'git & github'],
        'industries' => ['technology', 'education'],
        'programs' => ['bachelor of science in information technology'],
    ]);
});

afterEach(function () {
    ResumeLineFeaturizer::setGazetteers(null);
});

function fixture(string $name): string
{
    return __DIR__ . '/../fixtures/resumes/' . $name;
}

/** @param array<int,Line> $lines */
function indexOfLine(array $lines, string $needle): int
{
    foreach ($lines as $i => $line) {
        if (str_contains($line->text, $needle)) {
            return $i;
        }
    }

    return -1;
}

/** @param array<int,Line> $lines */
function findLine(array $lines, string $needle): ?Line
{
    $index = indexOfLine($lines, $needle);

    return $index === -1 ? null : $lines[$index];
}

it('extracts a single-column resume using real layout data', function () {
    $result = (new ResumeLineFeaturizer())->fromFile(fixture('app-template-single-column.pdf'));

    expect($result['mode'])->toBe(ResumeLineFeaturizer::MODE_LAYOUT)
        ->and($result['page_count'])->toBe(1)
        ->and(count($result['lines']))->toBeGreaterThan(15);
});

it('reads bold, italic and font size off the PDF rather than guessing from text', function () {
    $lines = (new ResumeLineFeaturizer())->fromFile(fixture('app-template-single-column.pdf'))['lines'];

    $name = findLine($lines, 'RYZA ISON');
    $header = findLine($lines, 'PROFESSIONAL SUMMARY');
    $body = findLine($lines, 'Aspiring full stack developer');
    $subtitle = findLine($lines, 'Pamantasan ng Lungsod');

    expect($name)->not->toBeNull()
        ->and($header)->not->toBeNull()
        ->and($body)->not->toBeNull()
        ->and($subtitle)->not->toBeNull();

    // The whole premise of the approach: headings are identifiable as headings
    // without matching their words.
    expect($header->bold)->toBeTrue()
        ->and($body->bold)->toBeFalse()
        ->and($subtitle->italic)->toBeTrue()
        ->and($name->size)->toBeGreaterThan($header->size)
        ->and($header->size)->toBeGreaterThan($body->size);
});

it('records a larger gap above a section heading than within a block', function () {
    $lines = (new ResumeLineFeaturizer())->fromFile(fixture('app-template-single-column.pdf'))['lines'];

    $header = findLine($lines, 'WORK EXPERIENCE');
    $subtitle = findLine($lines, 'Pamantasan ng Lungsod');

    expect($header->gapAbove)->toBeGreaterThan($subtitle->gapAbove);
});

it('splits one baseline into fragments where a wide horizontal gap separates content', function () {
    $lines = (new ResumeLineFeaturizer())->fromFile(fixture('app-template-single-column.pdf'))['lines'];

    $degree = findLine($lines, 'Bachelor of Science');
    $batch = findLine($lines, 'Batch 2023');

    expect($degree)->not->toBeNull()
        ->and($batch)->not->toBeNull()
        // Same visual row, two logical pieces.
        ->and($batch->rowKey)->toBe($degree->rowKey)
        ->and($degree->isRowFragment())->toBeTrue()
        ->and($batch->fragmentIndex)->toBeGreaterThan($degree->fragmentIndex);
});

it('keeps separately positioned skills as separate fragments', function () {
    $lines = (new ResumeLineFeaturizer())->fromFile(fixture('app-template-single-column.pdf'))['lines'];

    // Merging these would hide individual skills behind one blob.
    foreach (['PHP', 'Laravel', 'JavaScript'] as $skill) {
        expect(findLine($lines, $skill))->not->toBeNull();
    }
});

it('reads a two-column page one column at a time', function () {
    $lines = (new ResumeLineFeaturizer())->fromFile(fixture('two-column.pdf'))['lines'];

    $leftLast = max(indexOfLine($lines, 'SKILLS'), indexOfLine($lines, 'Figma'));
    $rightFirst = indexOfLine($lines, 'MARIA REYES');

    expect($leftLast)->toBeGreaterThan(-1)
        ->and($rightFirst)->toBeGreaterThan(-1)
        // Without column separation the two columns interleave and the
        // sidebar's skills land in the middle of the work history.
        ->and($rightFirst)->toBeGreaterThan($leftLast);

    $summary = indexOfLine($lines, 'Backend developer focused');
    $experience = indexOfLine($lines, 'WORK EXPERIENCE');
    expect($experience)->toBeGreaterThan($summary);
});

it('does not mistake a single-column layout for two columns', function () {
    $lines = (new ResumeLineFeaturizer())->fromFile(fixture('app-template-single-column.pdf'))['lines'];

    $order = [
        indexOfLine($lines, 'PROFESSIONAL SUMMARY'),
        indexOfLine($lines, 'EDUCATION'),
        indexOfLine($lines, 'SKILLS'),
        indexOfLine($lines, 'WORK EXPERIENCE'),
        indexOfLine($lines, 'CERTIFICATIONS'),
    ];

    expect($order)->not->toContain(-1);

    $sorted = $order;
    sort($sorted);
    expect($order)->toBe($sorted);
});

it('falls back to plain text lines when there is no usable layout', function () {
    $lines = (new ResumeLineFeaturizer())->linesFromRawText("MARIA REYES\n\n  SKILLS  \nPHP\n\n\nLaravel\n");

    expect($lines)->toHaveCount(4)
        ->and($lines[0]->text)->toBe('MARIA REYES')
        // Whitespace collapsed, blank lines dropped.
        ->and($lines[1]->text)->toBe('SKILLS')
        ->and($lines[0]->size)->toBe(0.0)
        ->and($lines[0]->bold)->toBeFalse();
});

it('marks the degraded regime so the model can treat it differently', function () {
    $featurizer = new ResumeLineFeaturizer();
    $lines = $featurizer->linesFromRawText("MARIA REYES\nSKILLS");

    $layout = $featurizer->staticFeatures($lines, ResumeLineFeaturizer::MODE_LAYOUT);
    $textOnly = $featurizer->staticFeatures($lines, ResumeLineFeaturizer::MODE_TEXT_ONLY);

    expect($textOnly[0])->toContain('no_layout')
        ->and($layout[0])->not->toContain('no_layout');
});

it('derives font size features relative to the document, not absolute points', function () {
    $featurizer = new ResumeLineFeaturizer();

    $make = fn (float $size) => new Line(
        text: 'Heading', page: 1, x: 10, y: 100, size: $size,
        bold: true, italic: false, gapAbove: 20, rowKey: 0, fragmentIndex: 0, fragmentCount: 1,
    );

    // Same relative shape at wildly different absolute sizes must featurize
    // identically, otherwise nothing transfers between a slide-style CV and a
    // dense one.
    $small = $featurizer->staticFeatures([$make(20.0), $make(10.0), $make(10.0)], ResumeLineFeaturizer::MODE_LAYOUT);
    $large = $featurizer->staticFeatures([$make(108.0), $make(54.0), $make(54.0)], ResumeLineFeaturizer::MODE_LAYOUT);

    $sizeFeature = fn (array $features) => implode(',', array_filter($features, fn ($f) => str_starts_with($f, 'sz:')));

    expect($sizeFeature($small[0]))->toBe($sizeFeature($large[0]))
        ->and($sizeFeature($small[0]))->not->toBe($sizeFeature($small[1]));
});

it('detects shape signals used to tell bullets, dates and contacts apart', function () {
    $featurizer = new ResumeLineFeaturizer();

    $make = fn (string $text) => new Line(
        text: $text, page: 1, x: 10, y: 100, size: 10,
        bold: false, italic: false, gapAbove: 5, rowKey: 0, fragmentIndex: 0, fragmentCount: 1,
    );

    $lines = [
        $make('• Built reporting endpoints for the finance team'),
        $make('Jan 2020 - Mar 2022'),
        $make('maria.reyes@example.com'),
        $make('WORK EXPERIENCE'),
        $make('Developed APIs using PHP, Laravel and MySQL'),
    ];

    $features = $featurizer->staticFeatures($lines, ResumeLineFeaturizer::MODE_LAYOUT);

    expect($features[0])->toContain('bullet')
        ->and($features[1])->toContain('daterange')
        ->and($features[2])->toContain('email')
        ->and($features[3])->toContain('caps')
        ->and($features[4])->toContain('gazskill:2');
});

it('conjoins the previous label and current section, since either alone barely sequences', function () {
    $featurizer = new ResumeLineFeaturizer();
    $lines = [new Line(
        text: 'Backend Developer', page: 1, x: 50, y: 100, size: 10,
        bold: true, italic: false, gapAbove: 5, rowKey: 0, fragmentIndex: 0, fragmentCount: 1,
    )];

    $features = $featurizer->dynamicFeatures($lines, 0, 'header_experience', 'experience');

    expect($features)->toContain('prev:header_experience')
        ->and($features)->toContain('prev:header_experience|bold')
        ->and($features)->toContain('sect:experience')
        ->and($features)->toContain('sect:experience|bold');

    $atStart = $featurizer->dynamicFeatures($lines, 0, null, null);
    expect($atStart)->toContain('prev:<start>')->and($atStart)->toContain('sect:<none>');
});

it('changes its fingerprint and drops features when a group is ablated', function () {
    $full = new ResumeLineFeaturizer();
    $noTypography = new ResumeLineFeaturizer(['typography']);

    expect($noTypography->configFingerprint())->not->toBe($full->configFingerprint());

    $lines = [new Line(
        text: 'WORK EXPERIENCE', page: 1, x: 10, y: 100, size: 14,
        bold: true, italic: false, gapAbove: 20, rowKey: 0, fragmentIndex: 0, fragmentCount: 1,
    )];

    expect($full->staticFeatures($lines, ResumeLineFeaturizer::MODE_LAYOUT)[0])->toContain('bold')
        ->and($noTypography->staticFeatures($lines, ResumeLineFeaturizer::MODE_LAYOUT)[0])->not->toContain('bold');

    // Ablation must not change the fingerprint only — cached features keyed on
    // it would otherwise be reused across incompatible configurations.
    expect((new ResumeLineFeaturizer(['typography']))->configFingerprint())
        ->toBe($noTypography->configFingerprint());
});

it('never matches a gazetteer entry inside a longer word', function () {
    $featurizer = new ResumeLineFeaturizer();
    ResumeLineFeaturizer::setGazetteers([
        'skills' => [],
        // 'None' is a real industries row; substring matching is what makes the
        // existing heuristic parser tag any resume mentioning a telephone.
        'industries' => ['none'],
        'programs' => [],
    ]);

    $lines = [new Line(
        text: 'Telephone: 0917 555 0101', page: 1, x: 10, y: 100, size: 10,
        bold: false, italic: false, gapAbove: 5, rowKey: 0, fragmentIndex: 0, fragmentCount: 1,
    )];

    expect($featurizer->staticFeatures($lines, ResumeLineFeaturizer::MODE_LAYOUT)[0])
        ->not->toContain('hasindustry');
});

it('round-trips a line through persistence without losing geometry', function () {
    $line = new Line(
        text: 'Backend Developer', page: 2, x: 34.5, y: 541.6, size: 8.25,
        bold: true, italic: false, gapAbove: 20.0, rowKey: 7, fragmentIndex: 1, fragmentCount: 2,
    );

    $restored = Line::fromArray($line->toArray());

    expect($restored->text)->toBe($line->text)
        ->and($restored->page)->toBe($line->page)
        ->and($restored->bold)->toBeTrue()
        ->and($restored->fragmentCount)->toBe(2)
        ->and($restored->isRowFragment())->toBeTrue()
        ->and($restored->size)->toBe(8.25);
});
